const { PDFDocument, rgb, StandardFonts } = require('pdf-lib');
const { verifyAuditIntegrity } = require('./audit.service');

const generateCSV = (logs) => {
  const headers = ['Timestamp', 'Actor Name', 'Actor Email', 'Action', 'Target ID', 'Result', 'IP Address'];
  const rows = logs.map(log => [
    new Date(log.timestamp).toISOString(),
    log.actorId?.name || 'System',
    log.actorId?.email || '',
    log.action,
    log.targetDocumentId || log.targetCaseId || log.targetUserId || '',
    log.result,
    log.ipAddress || ''
  ]);
  
  const csvContent = [
    headers.join(','),
    ...rows.map(row => row.map(v => `"${v}"`).join(','))
  ].join('\n');
  
  return Buffer.from(csvContent);
};

const generatePDF = async (logs, generatedBy, filters = {}) => {
  // First, verify integrity to include in report
  const integrity = await verifyAuditIntegrity();
  const integrityStatus = integrity.isVerified ? 'VERIFIED' : 'TAMPERING DETECTED';
  
  const pdfDoc = await PDFDocument.create();
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
  
  let page = pdfDoc.addPage([842, 595]); // A4 Landscape
  const { width, height } = page.getSize();
  
  // Header
  page.drawText('SecureDocs Compliance Report', { x: 50, y: height - 50, size: 20, font: boldFont });
  page.drawText(`Generated By: ${generatedBy.name} (${generatedBy.email})`, { x: 50, y: height - 75, size: 12, font });
  page.drawText(`Generated At: ${new Date().toISOString()}`, { x: 50, y: height - 90, size: 12, font });
  
  // Integrity verification result
  const statusColor = integrity.isVerified ? rgb(0, 0.5, 0) : rgb(0.8, 0, 0);
  page.drawText(`Audit Ledger Integrity: ${integrityStatus}`, { 
    x: width - 300, y: height - 50, size: 14, font: boldFont, color: statusColor 
  });
  
  // Filters info
  let yOffset = height - 120;
  if (Object.keys(filters).length > 0) {
    page.drawText(`Filters applied: ${JSON.stringify(filters)}`, { x: 50, y: yOffset, size: 10, font, color: rgb(0.4, 0.4, 0.4) });
  }
  
  yOffset -= 30;
  
  // Table headers
  const headers = ['Timestamp', 'Actor', 'Action', 'Target', 'Result', 'IP Address'];
  const colWidths = [120, 150, 150, 150, 80, 100];
  let xOffset = 50;
  
  headers.forEach((header, i) => {
    page.drawText(header, { x: xOffset, y: yOffset, size: 10, font: boldFont });
    xOffset += colWidths[i];
  });
  
  page.drawLine({ start: { x: 50, y: yOffset - 5 }, end: { x: width - 50, y: yOffset - 5 }, thickness: 1 });
  yOffset -= 20;
  
  // Draw rows
  for (const log of logs) {
    if (yOffset < 50) {
      page = pdfDoc.addPage([842, 595]);
      yOffset = height - 50;
    }
    
    xOffset = 50;
    
    // Format text to avoid overflowing
    const rowData = [
      new Date(log.timestamp).toISOString().split('T')[0] + ' ' + new Date(log.timestamp).toISOString().split('T')[1].slice(0, 8),
      (log.actorId?.name || 'System').substring(0, 25),
      log.action,
      (log.targetDocumentId || log.targetCaseId || log.targetUserId || '').toString().substring(0, 20),
      log.result,
      log.ipAddress || ''
    ];
    
    rowData.forEach((text, i) => {
      page.drawText(text, { x: xOffset, y: yOffset, size: 9, font });
      xOffset += colWidths[i];
    });
    
    yOffset -= 15;
  }
  
  const pdfBytes = await pdfDoc.save();
  return Buffer.from(pdfBytes);
};

module.exports = {
  generateCSV,
  generatePDF
};
